### ISSUE TITLE
NPM or Yarn? We must choose!

### ISSUE THREAD

**Issue by christianh814** [open-gitops/website#70]
There has been issues ([example](https://github.com/open-gitops/website/runs/5188644224?check_suite_focus=true#step:4:13)) with respect to merging because the doc says that you can use `npm` or `yarn`, but in fact, you can only use `npm`  because that's what the github action is set to only use NPM.

Here are suggestions

* We use either `npm` or `yarn` and update the README to tell users to use the chosen one.
* OR, make the github action "smarter" by taking into account that a user could have used either one.

In any even, we should prevent this issue from happening.

**Comment by niklasmtj** [comment]
As someone who got bitten by this yesterday I would also say that we should put this into the `README`. I should have taken a look into the GitHub Actions workflow to see that we build the site with `npm ci` so I would have ran into the issue before pushing my changes to the repo and creating this Actions issue. 


The newer versions of `npm` seem to update the `package-lock.json` and if found the `yarn.lock` file when installing fresh dependencies. But it seems that the other way around is not the case. 
So I would vote for testing with `npm` before opening a PR. Even if I made the mistake yesterday 😀 

I also thought about a github action running on every PR which simply runs `npm ci` and `npm run build` to see if it pass or otherwise block the PR. Since the dependencies are cached this should just take a couple of seconds.

**Comment by strantalis** [comment]
I am just dropping my thoughts. I had no issues getting the site up and running locally, but I tend to gravitate towards npm.

I am also running node 17 and tried 16 but didn't seem to run into issues with `npm run develop`. Maybe because some packages are already cached locally?

**Comment by chris-short** [comment]
Just a note that Node v14 goes end of life next year (2023-04-30). The current LTS is 16. I'm not sure if that makes any impact here but, worth noting.

Source: https://nodejs.org/en/about/releases/

**Comment by strantalis** [comment]
@niklasmtj I have sometime this week where I could update the readme and add a GitHub action that runs npm ci and a lint job on a pull request if you want.

**Comment by niklasmtj** [comment]
@strantalis that would be a great idea! This way we can be sure that a build will succeed when merged.
